insert into Country (id,name,code) values(NULL,'Afghanistan','AF');
insert into Country (id,name,code) values(NULL,'Ã…land Islands','AX');
insert into Country (id,name,code) values(NULL,'Albania','AL');
insert into Country (id,name,code) values(NULL,'Algeria','DZ');
insert into Country (id,name,code) values(NULL,'American Samoa','AS');
insert into Country (id,name,code) values(NULL,'Andorra','AD');
insert into Country (id,name,code) values(NULL,'Angola','AO');
insert into Country (id,name,code) values(NULL,'Anguilla','AI');
insert into Country (id,name,code) values(NULL,'Antarctica','AQ');
insert into Country (id,name,code) values(NULL,'Antigua and Barbuda','AG');
insert into Country (id,name,code) values(NULL,'Argentina','AR');
insert into Country (id,name,code) values(NULL,'Armenia','AM');
insert into Country (id,name,code) values(NULL,'Aruba','AW');
insert into Country (id,name,code) values(NULL,'Australia','AU');
insert into Country (id,name,code) values(NULL,'Austria','AT');
insert into Country (id,name,code) values(NULL,'Azerbaijan','AZ');
insert into Country (id,name,code) values(NULL,'Bahamas','BS');
insert into Country (id,name,code) values(NULL,'Bahrain','BH');
insert into Country (id,name,code) values(NULL,'Bangladesh','BD');
insert into Country (id,name,code) values(NULL,'Barbados','BB');
insert into Country (id,name,code) values(NULL,'Belarus','BY');
insert into Country (id,name,code) values(NULL,'Belgium','BE');
insert into Country (id,name,code) values(NULL,'Belize','BZ');
insert into Country (id,name,code) values(NULL,'Benin','BJ');
insert into Country (id,name,code) values(NULL,'Bermuda','BM');
insert into Country (id,name,code) values(NULL,'Bhutan','BT');
insert into Country (id,name,code) values(NULL,'Bolivia, Plurinational State of','BO');
insert into Country (id,name,code) values(NULL,'Bonaire, Sint Eustatius and Saba','BQ');
insert into Country (id,name,code) values(NULL,'Bosnia and Herzegovina','BA');
insert into Country (id,name,code) values(NULL,'Botswana','BW');
insert into Country (id,name,code) values(NULL,'Bouvet Island','BV');
insert into Country (id,name,code) values(NULL,'Brazil','BR');
insert into Country (id,name,code) values(NULL,'British Indian Ocean Territory','IO');
insert into Country (id,name,code) values(NULL,'Brunei Darussalam','BN');
insert into Country (id,name,code) values(NULL,'Bulgaria','BG');
insert into Country (id,name,code) values(NULL,'Burkina Faso','BF');
insert into Country (id,name,code) values(NULL,'Burundi','BI');
insert into Country (id,name,code) values(NULL,'Cambodia','KH');
insert into Country (id,name,code) values(NULL,'Cameroon','CM');
insert into Country (id,name,code) values(NULL,'Canada','CA');
insert into Country (id,name,code) values(NULL,'Cape Verde','CV');
insert into Country (id,name,code) values(NULL,'Cayman Islands','KY');
insert into Country (id,name,code) values(NULL,'Central African Republic','CF');
insert into Country (id,name,code) values(NULL,'Chad','TD');
insert into Country (id,name,code) values(NULL,'Chile','CL');
insert into Country (id,name,code) values(NULL,'China','CN');
insert into Country (id,name,code) values(NULL,'Christmas Island','CX');
insert into Country (id,name,code) values(NULL,'Cocos (Keeling) Islands','CC');
insert into Country (id,name,code) values(NULL,'Colombia','CO');
insert into Country (id,name,code) values(NULL,'Comoros','KM');
insert into Country (id,name,code) values(NULL,'Congo','CG');
insert into Country (id,name,code) values(NULL,'Congo, the Democratic Republic of the','CD');
insert into Country (id,name,code) values(NULL,'Cook Islands','CK');
insert into Country (id,name,code) values(NULL,'Costa Rica','CR');
insert into Country (id,name,code) values(NULL,'CÃ´te d\'Ivoire','CI');
insert into Country (id,name,code) values(NULL,'Croatia','HR');
insert into Country (id,name,code) values(NULL,'Cuba','CU');
insert into Country (id,name,code) values(NULL,'CuraÃ§ao','CW');
insert into Country (id,name,code) values(NULL,'Cyprus','CY');
insert into Country (id,name,code) values(NULL,'Czech Republic','CZ');
insert into Country (id,name,code) values(NULL,'Denmark','DK');
insert into Country (id,name,code) values(NULL,'Djibouti','DJ');
insert into Country (id,name,code) values(NULL,'Dominica','DM');
insert into Country (id,name,code) values(NULL,'Dominican Republic','DO');
insert into Country (id,name,code) values(NULL,'Ecuador','EC');
insert into Country (id,name,code) values(NULL,'Egypt','EG');
insert into Country (id,name,code) values(NULL,'El Salvador','SV');
insert into Country (id,name,code) values(NULL,'Equatorial Guinea','GQ');
insert into Country (id,name,code) values(NULL,'Eritrea','ER');
insert into Country (id,name,code) values(NULL,'Estonia','EE');
insert into Country (id,name,code) values(NULL,'Ethiopia','ET');
insert into Country (id,name,code) values(NULL,'Falkland Islands (Malvinas)','FK');
insert into Country (id,name,code) values(NULL,'Faroe Islands','FO');
insert into Country (id,name,code) values(NULL,'Fiji','FJ');
insert into Country (id,name,code) values(NULL,'Finland','FI');
insert into Country (id,name,code) values(NULL,'France','FR');
insert into Country (id,name,code) values(NULL,'French Guiana','GF');
insert into Country (id,name,code) values(NULL,'French Polynesia','PF');
insert into Country (id,name,code) values(NULL,'French Southern Territories','TF');
insert into Country (id,name,code) values(NULL,'Gabon','GA');
insert into Country (id,name,code) values(NULL,'Gambia','GM');
insert into Country (id,name,code) values(NULL,'Georgia','GE');
insert into Country (id,name,code) values(NULL,'Germany','DE');
insert into Country (id,name,code) values(NULL,'Ghana','GH');
insert into Country (id,name,code) values(NULL,'Gibraltar','GI');
insert into Country (id,name,code) values(NULL,'Greece','GR');
insert into Country (id,name,code) values(NULL,'Greenland','GL');
insert into Country (id,name,code) values(NULL,'Grenada','GD');
insert into Country (id,name,code) values(NULL,'Guadeloupe','GP');
insert into Country (id,name,code) values(NULL,'Guam','GU');
insert into Country (id,name,code) values(NULL,'Guatemala','GT');
insert into Country (id,name,code) values(NULL,'Guernsey','GG');
insert into Country (id,name,code) values(NULL,'Guinea','GN');
insert into Country (id,name,code) values(NULL,'Guinea-Bissau','GW');
insert into Country (id,name,code) values(NULL,'Guyana','GY');
insert into Country (id,name,code) values(NULL,'Haiti','HT');
insert into Country (id,name,code) values(NULL,'Heard Island and McDonald Islands','HM');
insert into Country (id,name,code) values(NULL,'Holy See (Vatican City State)','VA');
insert into Country (id,name,code) values(NULL,'Honduras','HN');
insert into Country (id,name,code) values(NULL,'Hong Kong','HK');
insert into Country (id,name,code) values(NULL,'Hungary','HU');
insert into Country (id,name,code) values(NULL,'Iceland','IS');
insert into Country (id,name,code) values(NULL,'India','IN');
insert into Country (id,name,code) values(NULL,'Indonesia','ID');
insert into Country (id,name,code) values(NULL,'Iran, Islamic Republic of','IR');
insert into Country (id,name,code) values(NULL,'Iraq','IQ');
insert into Country (id,name,code) values(NULL,'Ireland','IE');
insert into Country (id,name,code) values(NULL,'Isle of Man','IM');
insert into Country (id,name,code) values(NULL,'Israel','IL');
insert into Country (id,name,code) values(NULL,'Italy','IT');
insert into Country (id,name,code) values(NULL,'Jamaica','JM');
insert into Country (id,name,code) values(NULL,'Japan','JP');
insert into Country (id,name,code) values(NULL,'Jersey','JE');
insert into Country (id,name,code) values(NULL,'Jordan','JO');
insert into Country (id,name,code) values(NULL,'Kazakhstan','KZ');
insert into Country (id,name,code) values(NULL,'Kenya','KE');
insert into Country (id,name,code) values(NULL,'Kiribati','KI');
insert into Country (id,name,code) values(NULL,'Korea, Democratic People\'s Republic of','KP');
insert into Country (id,name,code) values(NULL,'Korea, Republic of','KR');
insert into Country (id,name,code) values(NULL,'Kuwait','KW');
insert into Country (id,name,code) values(NULL,'Kyrgyzstan','KG');
insert into Country (id,name,code) values(NULL,'Lao People\'s Democratic Republic','LA');
insert into Country (id,name,code) values(NULL,'Latvia','LV');
insert into Country (id,name,code) values(NULL,'Lebanon','LB');
insert into Country (id,name,code) values(NULL,'Lesotho','LS');
insert into Country (id,name,code) values(NULL,'Liberia','LR');
insert into Country (id,name,code) values(NULL,'Libya','LY');
insert into Country (id,name,code) values(NULL,'Liechtenstein','LI');
insert into Country (id,name,code) values(NULL,'Lithuania','LT');
insert into Country (id,name,code) values(NULL,'Luxembourg','LU');
insert into Country (id,name,code) values(NULL,'Macao','MO');
insert into Country (id,name,code) values(NULL,'Macedonia, the Former Yugoslav Republic of','MK');
insert into Country (id,name,code) values(NULL,'Madagascar','MG');
insert into Country (id,name,code) values(NULL,'Malawi','MW');
insert into Country (id,name,code) values(NULL,'Malaysia','MY');
insert into Country (id,name,code) values(NULL,'Maldives','MV');
insert into Country (id,name,code) values(NULL,'Mali','ML');
insert into Country (id,name,code) values(NULL,'Malta','MT');
insert into Country (id,name,code) values(NULL,'Marshall Islands','MH');
insert into Country (id,name,code) values(NULL,'Martinique','MQ');
insert into Country (id,name,code) values(NULL,'Mauritania','MR');
insert into Country (id,name,code) values(NULL,'Mauritius','MU');
insert into Country (id,name,code) values(NULL,'Mayotte','YT');
insert into Country (id,name,code) values(NULL,'Mexico','MX');
insert into Country (id,name,code) values(NULL,'Micronesia, Federated States of','FM');
insert into Country (id,name,code) values(NULL,'Moldova, Republic of','MD');
insert into Country (id,name,code) values(NULL,'Monaco','MC');
insert into Country (id,name,code) values(NULL,'Mongolia','MN');
insert into Country (id,name,code) values(NULL,'Montenegro','ME');
insert into Country (id,name,code) values(NULL,'Montserrat','MS');
insert into Country (id,name,code) values(NULL,'Morocco','MA');
insert into Country (id,name,code) values(NULL,'Mozambique','MZ');
insert into Country (id,name,code) values(NULL,'Myanmar','MM');
insert into Country (id,name,code) values(NULL,'Namibia','NA');
insert into Country (id,name,code) values(NULL,'Nauru','NR');
insert into Country (id,name,code) values(NULL,'Nepal','NP');
insert into Country (id,name,code) values(NULL,'Netherlands','NL');
insert into Country (id,name,code) values(NULL,'New Caledonia','NC');
insert into Country (id,name,code) values(NULL,'New Zealand','NZ');
insert into Country (id,name,code) values(NULL,'Nicaragua','NI');
insert into Country (id,name,code) values(NULL,'Niger','NE');
insert into Country (id,name,code) values(NULL,'Nigeria','NG');
insert into Country (id,name,code) values(NULL,'Niue','NU');
insert into Country (id,name,code) values(NULL,'Norfolk Island','NF');
insert into Country (id,name,code) values(NULL,'Northern Mariana Islands','MP');
insert into Country (id,name,code) values(NULL,'Norway','NO');
insert into Country (id,name,code) values(NULL,'Oman','OM');
insert into Country (id,name,code) values(NULL,'Pakistan','PK');
insert into Country (id,name,code) values(NULL,'Palau','PW');
insert into Country (id,name,code) values(NULL,'Palestine, State of','PS');
insert into Country (id,name,code) values(NULL,'Panama','PA');
insert into Country (id,name,code) values(NULL,'Papua New Guinea','PG');
insert into Country (id,name,code) values(NULL,'Paraguay','PY');
insert into Country (id,name,code) values(NULL,'Peru','PE');
insert into Country (id,name,code) values(NULL,'Philippines','PH');
insert into Country (id,name,code) values(NULL,'Pitcairn','PN');
insert into Country (id,name,code) values(NULL,'Poland','PL');
insert into Country (id,name,code) values(NULL,'Portugal','PT');
insert into Country (id,name,code) values(NULL,'Puerto Rico','PR');
insert into Country (id,name,code) values(NULL,'Qatar','QA');
insert into Country (id,name,code) values(NULL,'RÃ©union','RE');
insert into Country (id,name,code) values(NULL,'Romania','RO');
insert into Country (id,name,code) values(NULL,'Russian Federation','RU');
insert into Country (id,name,code) values(NULL,'Rwanda','RW');
insert into Country (id,name,code) values(NULL,'Saint BarthÃ©lemy','BL');
insert into Country (id,name,code) values(NULL,'Saint Helena, Ascension and Tristan da Cunha','SH');
insert into Country (id,name,code) values(NULL,'Saint Kitts and Nevis','KN');
insert into Country (id,name,code) values(NULL,'Saint Lucia','LC');
insert into Country (id,name,code) values(NULL,'Saint Martin (French part)','MF');
insert into Country (id,name,code) values(NULL,'Saint Pierre and Miquelon','PM');
insert into Country (id,name,code) values(NULL,'Saint Vincent and the Grenadines','VC');
insert into Country (id,name,code) values(NULL,'Samoa','WS');
insert into Country (id,name,code) values(NULL,'San Marino','SM');
insert into Country (id,name,code) values(NULL,'Sao Tome and Principe','ST');
insert into Country (id,name,code) values(NULL,'Saudi Arabia','SA');
insert into Country (id,name,code) values(NULL,'Senegal','SN');
insert into Country (id,name,code) values(NULL,'Serbia','RS');
insert into Country (id,name,code) values(NULL,'Seychelles','SC');
insert into Country (id,name,code) values(NULL,'Sierra Leone','SL');
insert into Country (id,name,code) values(NULL,'Singapore','SG');
insert into Country (id,name,code) values(NULL,'Sint Maarten (Dutch part)','SX');
insert into Country (id,name,code) values(NULL,'Slovakia','SK');
insert into Country (id,name,code) values(NULL,'Slovenia','SI');
insert into Country (id,name,code) values(NULL,'Solomon Islands','SB');
insert into Country (id,name,code) values(NULL,'Somalia','SO');
insert into Country (id,name,code) values(NULL,'South Africa','ZA');
insert into Country (id,name,code) values(NULL,'South Georgia and the South Sandwich Islands','GS');
insert into Country (id,name,code) values(NULL,'South Sudan','SS');
insert into Country (id,name,code) values(NULL,'Spain','ES');
insert into Country (id,name,code) values(NULL,'Sri Lanka','LK');
insert into Country (id,name,code) values(NULL,'Sudan','SD');
insert into Country (id,name,code) values(NULL,'Suriname','SR');
insert into Country (id,name,code) values(NULL,'Svalbard and Jan Mayen','SJ');
insert into Country (id,name,code) values(NULL,'Swaziland','SZ');
insert into Country (id,name,code) values(NULL,'Sweden','SE');
insert into Country (id,name,code) values(NULL,'Switzerland','CH');
insert into Country (id,name,code) values(NULL,'Syrian Arab Republic','SY');
insert into Country (id,name,code) values(NULL,'Taiwan, Province of China','TW');
insert into Country (id,name,code) values(NULL,'Tajikistan','TJ');
insert into Country (id,name,code) values(NULL,'Tanzania, United Republic of','TZ');
insert into Country (id,name,code) values(NULL,'Thailand','TH');
insert into Country (id,name,code) values(NULL,'Timor-Leste','TL');
insert into Country (id,name,code) values(NULL,'Togo','TG');
insert into Country (id,name,code) values(NULL,'Tokelau','TK');
insert into Country (id,name,code) values(NULL,'Tonga','TO');
insert into Country (id,name,code) values(NULL,'Trinidad and Tobago','TT');
insert into Country (id,name,code) values(NULL,'Tunisia','TN');
insert into Country (id,name,code) values(NULL,'Turkey','TR');
insert into Country (id,name,code) values(NULL,'Turkmenistan','TM');
insert into Country (id,name,code) values(NULL,'Turks and Caicos Islands','TC');
insert into Country (id,name,code) values(NULL,'Tuvalu','TV');
insert into Country (id,name,code) values(NULL,'Uganda','UG');
insert into Country (id,name,code) values(NULL,'Ukraine','UA');
insert into Country (id,name,code) values(NULL,'United Arab Emirates','AE');
insert into Country (id,name,code) values(NULL,'United Kingdom','GB');
insert into Country (id,name,code) values(NULL,'United States','US');
insert into Country (id,name,code) values(NULL,'United States Minor Outlying Islands','UM');
insert into Country (id,name,code) values(NULL,'Uruguay','UY');
insert into Country (id,name,code) values(NULL,'Uzbekistan','UZ');
insert into Country (id,name,code) values(NULL,'Vanuatu','VU');
insert into Country (id,name,code) values(NULL,'Venezuela, Bolivarian Republic of','VE');
insert into Country (id,name,code) values(NULL,'Viet Nam','VN');
insert into Country (id,name,code) values(NULL,'Virgin Islands, British','VG');
insert into Country (id,name,code) values(NULL,'Virgin Islands, U.S.','VI');
insert into Country (id,name,code) values(NULL,'Wallis and Futuna','WF');
insert into Country (id,name,code) values(NULL,'Western Sahara','EH');
insert into Country (id,name,code) values(NULL,'Yemen','YE');
insert into Country (id,name,code) values(NULL,'Zambia','ZM');
insert into Country (id,name,code) values(NULL,'Zimbabwe','ZW');
